/*
	File:		ROMData.h

	Contains:	NewtonScript global data.

	Written by:	Newton Research Group.
*/

#if !defined(__ROMDATA__)
#define __ROMDATA__ 1

/*------------------------------------------------------------------------------
	R O M   D a t a

	This structure MUST match the partData generated by the NSConstData
	NTK project.
------------------------------------------------------------------------------*/

struct ConstNSData
{
	Ref	magicPointers;
	Ref	sortTables;				// -> RA(sortTables)
	Ref	rootContext;			// -> RA(rootContext)
	Ref	vars;						// -> RA(varsMapStarter)
	Ref	initGlobalsFunc;		// -> RA(bootInitNSGlobals)
	Ref	initScriptsFunc;		// -> RA(bootRunInitScripts)
	Ref	internalFunctions;	// -> RA(builtinFunctions)
	Ref	externalFunctions;	// -> RA(gFunky)			{ } for MessagePad, { OpenResFile, StuffHex,... } for NTK
	Ref	constantFunctions;	//								{ LocObj, ButtonBounds,... } for NTK
	Ref	plainCFunctions;
	Ref	storeParent;			// -> RA(storePrototype)
	Ref	soupParent;				// -> RA(soupPrototype)
	Ref	cursorParent;			// -> RA(cursorPrototype)
	Ref	clicks;					// -> RA(clicks)
#if defined(forNTK)
	Ref	formInstallScript;
	Ref	formRemoveScript;
	Ref	autoInstallScript;
#endif
};

extern ConstNSData * gConstNSData;

#endif	/* __ROMDATA__ */
