/*
	File:		ROMData.h

	Contains:	NewtonScript global data.

	Written by:	Newton Research Group.
*/

#if !defined(__ROMDATA__)
#define __ROMDATA__ 1

/*------------------------------------------------------------------------------
	R O M   D a t a

	This structure MUST match the partData generated by the NSConstData
	NTK project.
------------------------------------------------------------------------------*/

struct ConstNSData
{
	Ref	magicPointers;
	Ref	sortTables;
	Ref	rootContext;
	Ref	vars;
	Ref	initGlobalsFunc;
	Ref	initScriptsFunc;
	Ref	internalFunctions;
	Ref	externalFunctions;
	Ref	constantFunctions;
	Ref	plainCFunctions;
	Ref	storeParent;
	Ref	soupParent;
	Ref	cursorParent;
	Ref	clicks;
#if defined(forNTK)
	Ref	formInstallScript;
	Ref	formRemoveScript;
	Ref	autoInstallScript;
#endif
};

extern ConstNSData * gConstNSData;

#endif	/* __ROMDATA__ */
