/*
	File:		Globals.h

	Contains:	NewtonScript global data.

	Written by:	Newton Research Group.
*/

#if !defined(__GLOBALS__)
#define __GLOBALS__ 1

#include "NewtGlobals.h"


/*------------------------------------------------------------------------------
	G l o b a l   V a r i a b l e s
------------------------------------------------------------------------------*/

extern Ref		gVarFrame;
extern Ref *	RSgVarFrame;


/* -----------------------------------------------------------------------------
	D e b u g   O u t p u t
----------------------------------------------------------------------------- */

#if defined(__cplusplus)
extern "C" {
#endif

void		PrintObject(Ref obj, int indent);
int		REPprintf(const char * inFormat, ...);
void		REPflush(void);

#if defined(__cplusplus)
}
#endif


/*------------------------------------------------------------------------------
	R O M   D a t a

	This structure MUST match the partData generated by the NSConstData
	NTK project.
------------------------------------------------------------------------------*/

struct ConstNSData
{
	Ref	magicPointers;
	Ref	sortTables;
	Ref	rootContext;
	Ref	vars;
	Ref	initGlobalsFunc;
	Ref	initScriptsFunc;
	Ref	internalFunctions;
	Ref	externalFunctions;
	Ref	constantFunctions;
	Ref	plainCFunctions;
	Ref	storeParent;
	Ref	soupParent;
	Ref	cursorParent;
	Ref	clicks;
};

extern ConstNSData * gConstNSData;


/*------------------------------------------------------------------------------
	R O M   R e s o u r c e s
------------------------------------------------------------------------------*/

#include "ROMResources.h"


/*------------------------------------------------------------------------------
	M e m o r y   M a p
	Although we don’t actually have a ROM, we do have immutable resources:
	symbols, for example. Should we try to detect those?
------------------------------------------------------------------------------*/
#if defined(forMessagePad)
#define ISINROM(_r) (ULong(Ref(_r)) < 0x03800000)
#define NOTINROM(_r) (ULong(Ref(_r)) >= 0x03800000)
#define ISINPACKAGE(_r) (ULong(Ref(_r)) >= 0x60000000 && ULong(Ref(_r)) < 0x68000000)
#else
#define ISINROM(_r) NO
#define NOTINROM(_r) YES
#define ISINPACKAGE(_r) NO
#endif
#define ISRO(_r) (ISINROM(_r) || ISINPACKAGE(_r))

#endif	/* __GLOBALS__ */
